// Jede Plattform hat url, errorType und optional errorMsg/errorCode
// errorType: "status_code" = 404 bedeutet nicht gefunden
//            "message" = Seite gibt 200 aber enthält Fehlertext

module.exports = [
  { name: 'GitHub', url: 'https://github.com/{}', errorType: 'status_code' },
  { name: 'Reddit', url: 'https://www.reddit.com/user/{}', errorType: 'message', errorMsg: 'Sorry, nobody on Reddit goes by that name.' },
  { name: 'Twitter/X', url: 'https://twitter.com/{}', errorType: 'status_code' },
  { name: 'Instagram', url: 'https://www.instagram.com/{}', errorType: 'message', errorMsg: 'Sorry, this page isn\'t available.' },
  { name: 'TikTok', url: 'https://www.tiktok.com/@{}', errorType: 'message', errorMsg: "Couldn't find this account" },
  { name: 'YouTube', url: 'https://www.youtube.com/@{}', errorType: 'status_code' },
  { name: 'Twitch', url: 'https://www.twitch.tv/{}', errorType: 'status_code' },
  { name: 'Pinterest', url: 'https://www.pinterest.com/{}/', errorType: 'status_code' },
  { name: 'SoundCloud', url: 'https://soundcloud.com/{}', errorType: 'status_code' },
  { name: 'Steam', url: 'https://steamcommunity.com/id/{}', errorType: 'message', errorMsg: 'The specified profile could not be found.' },
  { name: 'Roblox', url: 'https://www.roblox.com/user.aspx?username={}', errorType: 'message', errorMsg: 'Page cannot be found' },
  { name: 'Spotify', url: 'https://open.spotify.com/user/{}', errorType: 'status_code' },
  { name: 'Kick', url: 'https://kick.com/{}', errorType: 'status_code' },
  { name: 'LinkedIn', url: 'https://www.linkedin.com/in/{}', errorType: 'status_code' },
  { name: 'Tumblr', url: 'https://{}.tumblr.com', errorType: 'message', errorMsg: 'There\'s nothing here.' },
  { name: 'DeviantArt', url: 'https://www.deviantart.com/{}', errorType: 'status_code' },
  { name: 'Patreon', url: 'https://www.patreon.com/{}', errorType: 'status_code' },
  { name: 'Fiverr', url: 'https://www.fiverr.com/{}', errorType: 'status_code' },
  { name: 'Replit', url: 'https://replit.com/@{}', errorType: 'status_code' },
  { name: 'GitLab', url: 'https://gitlab.com/{}', errorType: 'status_code' },
  { name: 'Keybase', url: 'https://keybase.io/{}', errorType: 'status_code' },
  { name: 'Letterboxd', url: 'https://letterboxd.com/{}', errorType: 'status_code' },
  { name: 'Last.fm', url: 'https://www.last.fm/user/{}', errorType: 'status_code' },
  { name: 'Flickr', url: 'https://www.flickr.com/people/{}', errorType: 'status_code' },
  { name: 'Vimeo', url: 'https://vimeo.com/{}', errorType: 'status_code' },
  { name: 'Medium', url: 'https://medium.com/@{}', errorType: 'status_code' },
  { name: 'Linktree', url: 'https://linktr.ee/{}', errorType: 'status_code' },
  { name: 'Ko-fi', url: 'https://ko-fi.com/{}', errorType: 'status_code' },
  { name: 'Behance', url: 'https://www.behance.net/{}', errorType: 'status_code' },
  { name: 'Dribbble', url: 'https://dribbble.com/{}', errorType: 'status_code' },
  { name: 'Hackerrank', url: 'https://www.hackerrank.com/{}', errorType: 'status_code' },
  { name: 'Leetcode', url: 'https://leetcode.com/{}', errorType: 'status_code' },
  { name: 'DockerHub', url: 'https://hub.docker.com/u/{}', errorType: 'status_code' },
  { name: 'ProductHunt', url: 'https://www.producthunt.com/@{}', errorType: 'status_code' },
  { name: 'Quora', url: 'https://www.quora.com/profile/{}', errorType: 'status_code' },
  { name: 'Bluesky', url: 'https://bsky.app/profile/{}', errorType: 'status_code' },
  { name: 'Chess.com', url: 'https://www.chess.com/member/{}', errorType: 'message', errorMsg: 'Oops! That page can\'t be found.' },
  { name: 'Duolingo', url: 'https://www.duolingo.com/profile/{}', errorType: 'status_code' },
  { name: 'Wattpad', url: 'https://www.wattpad.com/user/{}', errorType: 'status_code' },
  { name: 'Snapchat', url: 'https://www.snapchat.com/add/{}', errorType: 'message', errorMsg: 'Sorry! Couldn\'t find' },
  { name: 'Cashapp', url: 'https://cash.app/${}', errorType: 'status_code' },
  { name: 'Substack', url: 'https://{}.substack.com', errorType: 'status_code' },
  { name: 'Mastodon', url: 'https://mastodon.social/@{}', errorType: 'status_code' },
  { name: 'NPM', url: 'https://www.npmjs.com/~{}', errorType: 'status_code' },
  { name: 'Trello', url: 'https://trello.com/{}', errorType: 'status_code' },
  { name: 'Periscope', url: 'https://www.periscope.tv/{}', errorType: 'status_code' },
  { name: 'Venmo', url: 'https://venmo.com/{}', errorType: 'status_code' },
  { name: 'Codeforces', url: 'https://codeforces.com/profile/{}', errorType: 'message', errorMsg: 'handle: User with handle {} not found' },
  { name: 'Furaffinity', url: 'https://www.furaffinity.net/user/{}', errorType: 'message', errorMsg: 'This user cannot be found.' },
  { name: 'Minds', url: 'https://www.minds.com/{}', errorType: 'status_code' },
];
